version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Install SDK 21
          command: wget https://download.java.net/java/GA/jdk21.0.1/415e3f918a1f4062a0074a2794853d0d/12/GPL/openjdk-21.0.1_linux-x64_bin.tar.gz &&
            tar xvf openjdk-21.0.1_linux-x64_bin.tar.gz &&
            sudo mv jdk-21*/ /opt/jdk21 &&
            export JAVA_HOME=/opt/jdk21 &&
            echo "export JAVA_HOME=/opt/jdk21" >> ~/.bashrc &&
            echo "export PATH=$JAVA_HOME/bin:$PATH" >> ~/.bashrc

      - run:
          name: Build
          command: java -version &&
            mvn -B -DskipTests clean package

      - run:
          name: Test
          command: java -version &&
            make b

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
