version: 2
machine: true
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: JDK17 installation
          command: wget https://download.oracle.com/java/17/archive/jdk-17.0.3.1_linux-x64_bin.tar.gz -O jdk17.tar.gz && tar -xvzf jdk17.tar.gz && mv jdk-17* jdk17 && sudo mv jdk17 /opt/

      - run:
          name: All tests
          command: export JAVA_HOME=/opt/jdk17 && export PATH=$PATH::$JAVA_HOME/bin && mvn clean install -DskipTests && mvn test
