name: jeorg-spring-5-test-drives
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build
      run: mvn clean jacoco:prepare-agent install jacoco:report coveralls:report -DrepoToken=${COVERALLS_REPO_TOKEN}
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Coverage with Codecov
      run: bash <(curl -s https://codecov.io/bash)
      env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Coverage with Codacy
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java Kotlin $(find **/jacoco*.xml -printf '-r %p ')
      env:
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
